//Exception Handling -> allows you to handle errors so program doesnt crash

val divisor = 0

try {
    if (divisor == 0) {
        throw IllegalArgumentException("can't divide by zero")
    } else {
        println("5 / $divisor = ${5/divisor}")
    }
} catch(e: IllegalArgumentException) {
    println("${e.message}")
}